### PR TITLE
LPS-86726 Fix blog, poll, userGroup class name

### PR DESCRIPTION
**Pull request by foshiro-zz**
https://issues.liferay.com/browse/LPS-86726

### CODE REVIEW

**Comment by foshiro** [comment]
ci:test:sf

**Comment by foshiro** [comment]
ci:test:search

**Comment by foshiro-zz** [comment]
ci:test:sf

**Comment by foshiro-zz** [comment]
ci:test:search

**Comment by foshiro-zz** [comment]
ci:test:sf:norebase

**Pull request closed without merging**
